#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2021, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

# mvds host:remote_system_ds/disk.i fe:SOURCE vmid dsid
#   - fe is the front-end hostname
#   - SOURCE is the path of the disk image in the form DS_BASE_PATH/disk
#   - host is the target host to deploy the VM
#   - remote_system_ds is the path for the system datastore in the host
#   - vmid is the id of the VM
#   - dsid is the target datastore (0 is the system datastore)
# Nothing to do

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
    LIB_LOCATION=/usr/lib/one
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
    LIB_LOCATION=$ONE_LOCATION/lib
fi

DRIVER_PATH=$(dirname $0)

source $TMCOMMON
source ${DRIVER_PATH}/../../etc/datastore/zfs/zfs.conf
source ${DRIVER_PATH}/../../datastore/libfs.sh

ZFS_UTILS=${DRIVER_PATH}/../../datastore/zfs/zfs_utils.sh

#-------------------------------------------------------------------------------
# Process destination
#-------------------------------------------------------------------------------

SRC=$1
SRC_PATH="$(arg_path $SRC)"
SRC_HOST="$(arg_host $SRC)"

XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"

log "Deleting symbolic link $SRC_PATH"

MVDS_CMD=$(cat <<EOF
    SUDO="${SUDO}"

    rm $SRC_PATH
EOF
)

ssh_exec_and_log_stdin "$SRC_HOST" "$MVDS_CMD" "$ZFS_UTILS" \
                 "Error deleting $SRC_PATH in $SRC_HOST"
