#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2019, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

# clone fe:SOURCE host:remote_system_ds/disk.i size
#   - fe is the front-end hostname
#   - SOURCE is the path of the disk image in the form DS_BASE_PATH/disk
#   - host is the target host to deploy the VM
#   - remote_system_ds is the path for the system datastore in the host

SRC=$1
DST=$2
VM_ID=$3
DS_ID=$4

#--------------------------------------------------------------------------------

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
    LIB_LOCATION=/usr/lib/one
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
    LIB_LOCATION=$ONE_LOCATION/lib
fi

DRIVER_PATH=$(dirname $0)

source $TMCOMMON
source ${DRIVER_PATH}/../../etc/datastore/zfs_iscsi/zfs.conf
source ${DRIVER_PATH}/../../datastore/libfs.sh

ZFS_UTILS=${DRIVER_PATH}/../../datastore/zfs_iscsi/zfs_utils.sh

#-------------------------------------------------------------------------------
# Compute the destination image name
#-------------------------------------------------------------------------------

DST_HOST=`arg_host $DST`

SRC_PATH=`arg_path $SRC`
DST_PATH=`arg_path $DST`

DST_DIR=`dirname $DST_PATH`

DISK_ID=$(echo $DST|awk -F. '{print $NF}')
DST_DS_ID=$(echo $DST | sed s#//*#/#g | awk -F/ '{print $(NF-2)}')

#-------------------------------------------------------------------------------
# Get Image information
#-------------------------------------------------------------------------------

XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
        XPATH_ELEMENTS[i++]="$element"
done < <(onevm show -x $VM_ID| $XPATH  \
                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/SIZE \
                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/ORIGINAL_SIZE \
                    /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/DATASTORE_ID )

SIZE="${XPATH_ELEMENTS[j++]}"
ORIGINAL_SIZE="${XPATH_ELEMENTS[j++]}"
DATASTORE_ID="${XPATH_ELEMENTS[j++]}"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
        XPATH_ELEMENTS[i++]="$element"
done < <(onedatastore show -x $DATASTORE_ID| $XPATH  \
                    /DATASTORE/TEMPLATE/POOL_NAME \
                    /DATASTORE/TEMPLATE/BRIDGE_LIST \
                    /DATASTORE/TEMPLATE/ISCSI_USER \
		    /DATASTORE/TEMPLATE/ISCSI_PWD )

POOL_NAME="${XPATH_ELEMENTS[j++]:-$POOL_NAME}"
BRIDGE_LIST="${XPATH_ELEMENTS[j++]}"
ISCSI_USER="${XPATH_ELEMENTS[j++]}"
ISCSI_PWD="${XPATH_ELEMENTS[j++]:-$ISCSI_PWD}"

DST_HOST=`get_destination_host $VM_ID`

if [ -z "$DST_HOST" ]; then
    error_message "Datastore template missing 'BRIDGE_LIST' attribute.|${DRIVER_PATH}|"
    exit -1
fi

IMAGE_NAME=$(echo $SRC | awk -F: '{print $NF}')
ZVOL_SRC="$POOL_NAME/$IMAGE_NAME"
DST_NAME="$IMAGE_NAME-${VM_ID}-${DISK_ID}"
ZVOL_DST="$POOL_NAME/$DST_NAME"
ZVOL_DEV="/dev/zvol/${ZVOL_DST}"

ZVOL_IQN="$SRC-${VM_ID}-${DISK_ID}"

ISCSI_PWD=$(echo "$ISCSI_PWD" | base64 --decode)

#-------------------------------------------------------------------------------
# Clone the image and create @snap if it does not exists
#-------------------------------------------------------------------------------

CLONE_CMD=$(cat <<EOF
    SUDO="${SUDO}"

    $SUDO zfs list -H -r -o name $ZVOL_DST >/dev/null 2>&1 && exit 0

    zvol_make_snap $ZVOL_SRC

    set -e -o pipefail

    $SUDO zfs clone "$ZVOL_SRC@snap" $ZVOL_DST
    $SUDO zfs set refreservation=none $ZVOL_DST

    if [ -n "$ORIGINAL_SIZE" -a "$SIZE" -gt "$ORIGINAL_SIZE" ]; then
        $SUDO zfs set volsize=${SIZE}M $ZVOL_DST
    fi

    $SUDO targetcli /backstores/block create $DST_NAME $ZVOL_DEV
    $SUDO targetcli /backstores/block/$DST_NAME set attribute emulate_tpu=1
    $SUDO targetcli /iscsi create $ZVOL_IQN
    $SUDO targetcli /iscsi/$ZVOL_IQN/tpg1 set attribute authentication=1
    $SUDO targetcli /iscsi/$ZVOL_IQN/tpg1 set attribute generate_node_acls=1
    $SUDO targetcli /iscsi/$ZVOL_IQN/tpg1 set attribute demo_mode_write_protect=0
    $SUDO targetcli /iscsi/$ZVOL_IQN/tpg1 set auth userid=$ISCSI_USER
    $SUDO targetcli /iscsi/$ZVOL_IQN/tpg1 set auth password=$ISCSI_PWD
    $SUDO targetcli /iscsi/$ZVOL_IQN/tpg1/luns create /backstores/block/$DST_NAME
    $SUDO targetcli saveconfig

EOF
)

ssh_exec_and_log_stdin "$DST_HOST" "$CLONE_CMD" "$ZFS_UTILS" \
                 "Error cloning $ZVOL_SRC to $ZVOL_DST in $DST_HOST"

exit 0
