#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2019, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

###############################################################################
# This script is used to copy a VM image (SRC) to the image repository as DST
# Several SRC types are supported
###############################################################################
# -------- Set up the environment to source common tools & conf ------------
if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
else
    LIB_LOCATION=$ONE_LOCATION/lib
fi

. $LIB_LOCATION/sh/scripts_common.sh

DRIVER_PATH=$(dirname $0)
source ${DRIVER_PATH}/../libfs.sh
source ${DRIVER_PATH}/../../etc/datastore/zfs/zfs.conf

# -------- Get cp and datastore arguments from OpenNebula core ------------

DRV_ACTION=$1
ID=$2

XPATH="${DRIVER_PATH}/../xpath.rb -b $DRV_ACTION"

unset i XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH     /DS_DRIVER_ACTION_DATA/DATASTORE/BASE_PATH \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/BRIDGE_LIST \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/POOL_NAME \
                    /DS_DRIVER_ACTION_DATA/IMAGE/PATH \
		    /DS_DRIVER_ACTION_DATA/IMAGE/SIZE)

unset i

BASE_PATH="${XPATH_ELEMENTS[i++]}"
BRIDGE_LIST="${XPATH_ELEMENTS[i++]}"
POOL_NAME="${XPATH_ELEMENTS[i++]:-$POOL_NAME}"
SRC="${XPATH_ELEMENTS[i++]}"
SIZE="${XPATH_ELEMENTS[i++]}"

DST_HOST=`get_destination_host $ID`

if [ -z "$DST_HOST" ]; then
    error_message "Datastore template missing 'BRIDGE_LIST' attribute."
    exit -1
fi

SAFE_DIRS=""

IMAGE_NAME="one-${ID}"
ZVOL_SRC=$(echo $SRC | awk -F/ '{print $(NF-1)"/"$NF}')
ZVOL_DST="${POOL_NAME}/${IMAGE_NAME}"
ZVOL_DEV="/dev/zvol/$ZVOL_DST"

ZVOL_CLONE_CMD=$(cat <<EOF
    set -e -o pipefail

    $SUDO zfs snapshot $ZVOL_SRC@clone
    $SUDO zfs send $ZVOL_SRC@clone | $SUDO zfs receive $ZVOL_DST
    $SUDO zfs destroy $ZVOL_SRC@clone ; $SUDO zfs destroy $ZVOL_DST@clone 
    $SUDO zfs set refreservation=none $ZVOL_DST

    TIMEOUT=0
    until [ -b /dev/zvol/$ZVOL_DST ]; do
        sleep 1 && let "TIMEOUT +=1"
        if [ "$TIMEOUT" -gt "10" ]; then
            error_message "Error cloning $ZVOL_SRC to $ZVOL_DST in $DST_HOST, volume does not appear"
            exit -1
        fi
    done

EOF
)

ssh_exec_and_log "$DST_HOST" "$ZVOL_CLONE_CMD" \
                 "Error cloning $SRC to $ZVOL_DST in $DST_HOST"

echo "$ZVOL_DEV"
