#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2019, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

###############################################################################
# This script is used to remove a VM image (ZVOL_SRC) from the image repository
###############################################################################

# ------------ Set up the environment to source common tools ------------
if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
else
    LIB_LOCATION=$ONE_LOCATION/lib
fi

. $LIB_LOCATION/sh/scripts_common.sh

DRIVER_PATH=$(dirname $0)
ZFS_UTILS=${DRIVER_PATH}/zfs_utils.sh

source ${DRIVER_PATH}/../libfs.sh
source ${DRIVER_PATH}/../../etc/datastore/zfs_iscsi/zfs.conf

# -------- Get rm and datastore arguments from OpenNebula core ------------

DRV_ACTION=$1
ID=$2

XPATH="${DRIVER_PATH}/../xpath.rb -b $DRV_ACTION"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH     /DS_DRIVER_ACTION_DATA/IMAGE/SOURCE \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/BRIDGE_LIST \
		    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/POOL_NAME)

SRC="${XPATH_ELEMENTS[j++]}"
BRIDGE_LIST="${XPATH_ELEMENTS[j++]}"
POOL_NAME="${XPATH_ELEMENTS[j++]:-$POOL_NAME}"

IMAGE_NAME=$(echo $SRC | awk -F: '{print $NF}')
ZVOL_SRC="$POOL_NAME/$IMAGE_NAME"

DST_HOST=`get_destination_host $ID`

if [ -z "$DST_HOST" ]; then
    error_message "Datastore template missing 'BRIDGE_LIST' attribute."
    exit -1
fi

# -------- Remove Image from Datastore ------------

log "Removing $ZVOL_SRC from the zvol image repository in $DST_HOST"

DELETE_CMD=$(cat <<EOF
    set -e -o pipefail

    SUDO="${SUDO}"

    $SUDO targetcli /backstores/block delete $IMAGE_NAME
    $SUDO targetcli /iscsi delete $SRC
    $SUDO targetcli saveconfig
 
    zvol_rm_r \$(zvol_top_parent $ZVOL_SRC)
EOF
)

ssh_exec_and_log_stdin "$DST_HOST" "$DELETE_CMD" "$ZFS_UTILS" \
                 "Error deleting $ZVOL_SRC in $DST_HOST"
